use std::io::Read;

const REPOS: &[(&str, &str)] = &[
    ("torvalds/linux", "master"),
    ("python/cpython", "main"),
    ("rust-lang/rust", "master"),
    ("microsoft/vscode", "main"),
    ("golang/go", "master"),
    ("nodejs/node", "main"),
];

const SOURCE_EXTENSIONS: &[&str] = &[
    ".rs", ".py", ".c", ".h", ".cpp", ".hpp", ".cc", ".js", ".ts", ".jsx", ".tsx", ".go", ".java",
    ".rb", ".swift", ".zig", ".cs", ".php", ".lua", ".sh", ".bash", ".toml", ".yaml", ".yml",
    ".json", ".xml",
];

fn is_source_file(path: &str) -> bool {
    let lower = path.to_ascii_lowercase();
    SOURCE_EXTENSIONS.iter().any(|ext| lower.ends_with(ext))
}

fn main() {
    let mut counts = [[0u64; 256]; 256];
    let mut total_bytes: u64 = 0;
    let mut total_files: u64 = 0;

    for (repo, branch) in REPOS {
        let url = format!(
            "https://github.com/{}/archive/refs/heads/{}.tar.gz",
            repo, branch
        );
        eprintln!("streaming {}...", repo);

        let response = match ureq::get(&url).call() {
            Ok(r) => r,
            Err(e) => {
                eprintln!("  error fetching {}: {}", repo, e);
                continue;
            }
        };

        let reader = response.into_body().into_reader();
        let decoder = flate2::read::GzDecoder::new(reader);
        let mut archive = tar::Archive::new(decoder);

        let entries = match archive.entries() {
            Ok(e) => e,
            Err(e) => {
                eprintln!("  error reading archive for {}: {}", repo, e);
                continue;
            }
        };

        let mut repo_bytes: u64 = 0;
        let mut repo_files: u64 = 0;

        for entry in entries {
            let mut entry = match entry {
                Ok(e) => e,
                Err(_) => continue,
            };

            let path = match entry.path() {
                Ok(p) => p.to_string_lossy().to_string(),
                Err(_) => continue,
            };

            if !is_source_file(&path) {
                continue;
            }

            let size = entry.size();
            if size > 10 * 1024 * 1024 {
                continue; // skip files > 10MB
            }

            let mut buf = Vec::with_capacity(size as usize);
            if entry.read_to_end(&mut buf).is_err() {
                continue;
            }

            // skip binary files (null byte in first 8KB)
            let check_len = buf.len().min(8192);
            if buf[..check_len].contains(&0u8) {
                continue;
            }

            for pair in buf.windows(2) {
                counts[pair[0] as usize][pair[1] as usize] += 1;
            }

            repo_bytes += buf.len() as u64;
            repo_files += 1;
        }

        total_bytes += repo_bytes;
        total_files += repo_files;
        eprintln!(
            "  {} files, {:.1} MB",
            repo_files,
            repo_bytes as f64 / 1_048_576.0
        );
    }

    eprintln!(
        "\ntotal: {} files, {:.1} MB processed",
        total_files,
        total_bytes as f64 / 1_048_576.0
    );

    // Generate the .rs file
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by tools/generate_table.rs — do not edit manually.\n"
    ));
    out.push_str(&format!(
        "// Source: {} repos, {} files, {:.1} MB processed.\n\n",
        REPOS.len(),
        total_files,
        total_bytes as f64 / 1_048_576.0
    ));
    out.push_str("pub static WEIGHT: [[f32; 256]; 256] = [\n");

    for a in 0..256 {
        out.push_str("    [");
        for b in 0..256 {
            let w = 1.0 / (counts[a][b] as f64 + 1.0);
            if b > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{:.e}", w as f32));
        }
        out.push_str("],\n");
    }

    out.push_str("];\n");

    let output_path = "src/freq.rs";
    std::fs::write(output_path, &out).expect("failed to write freq.rs");
    eprintln!("wrote {}", output_path);
}
